version: '3.8'

services:
  # Tu aplicaci√≥n Web + API
  web:
    build: .
    ports:
      # CAMBIO CLAVE: Usamos el 8085 porque el 80 lo usa tu Nginx
      - "8085:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/examendb
    depends_on:
      - mongo
    restart: always

  # Base de Datos MongoDB
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persistencia de datos
    restart: always

volumes:
  mongo-data:
